### ISSUE TITLE
Unable to load Freestyle Libre data

### ISSUE THREAD

**Issue by KidneyNode** [MRCIEU/GLU#1]
Hi there,

I've been unable to load FreeStyle libre data, with the error message "Column missing from input file: Time"

In the CSV file, the time column is named "Device Timestamp"

**Comment by ltjansman** [comment]
I was hoping to find a solution to this. I'm running into the same issue with my libre data. I am really excited to try this package.

**Comment by louise** [comment]
Apologies for the slow response. This is now fixed. For any further issues please supply a minimal working example, e.g. the command you use to run GLU and some example (non sensitive test) data.
